language: node_js
node_js:
  - 0.10

branches:
  only:
    - master

env:
  global:
    - secure: ckul1NeOfQi13LxMvppoXzc/O08YEf2HqDbyE3dl2mgnjQVfB8ASRKSyvp6jZhKYEPX+WUwfdpHid8fGq3ESwTAUT41QF+HBUr7xdz6772m7Qm0nMJ94FaT7iL+2sR2O6WmqpWWktUSOkN4omI7xOv9b1MVHYiYPct965SM3SdI=
    - secure: gJlW/YbFeC7HAiFxH+M4Ia8BYP0n4PvLRT2bG5YgfFsRfF7yNkppCIt/cSxrl5SUhsT6UnArLVejP1nw6U6Pxu4KoOKdnWLnFjU2/qtU0IpEZDgex4u1wthxe37qd/fkNRq5U243c4N9UuY8YLJm0rDVYhxVsP1QQSymWThhis4=

before_install:
  # Turn off unneeded services to free some memory
  - sudo service mysql stop
  - sudo service memcached stop
  - sudo service postgresql stop

  # Add any apt repos we might need
  - echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/dsc.sources.list
  - curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
  - sudo add-apt-repository -y ppa:oae/deps
  - sudo apt-get update

  # Hilary dependencies
  - sudo apt-get install -qq graphicsmagick
  - sudo apt-get install -y -o Dpkg::Options::=--force-confnew cassandra=1.2.16 dsc12
  - sudo sed -i 's/-Xss180k/-Xss256k/g' /etc/cassandra/cassandra-env.sh
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /etc/cassandra/cassandra-env.sh"
  - sudo service cassandra stop
  - sudo service cassandra start
  - sudo service cassandra status
  - sudo apt-get install nginx
  - npm install -g grunt-cli

  # Install etherpad-lite
  - cd ..
  - wget https://s3-eu-west-1.amazonaws.com/oae-testing/travisci/etherpad-lite.tar.gz
  - tar -xzf etherpad-lite.tar.gz
  - cd etherpad-lite
  - node src/node/server.js &
  - cd ..

  # avocet-ui dependencies
  - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-i686.tar.bz2
  - tar xjf phantomjs-1.9.2-linux-i686.tar.bz2
  - sudo ln -fs pwd/phantomjs-1.9.2-linux-i686/bin/phantomjs /usr/local/bin/phantomjs
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  - git checkout 1.0.3
  - sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs

  # Configure avocet-ui / nginx
  - cd ../avocet-ui
  - npm install
  - "echo '{\"NGINX_USER\": \"root\",\"NGINX_GROUP\": \"root\",\"NGINX_HOSTNAME\": \"admin.oae.com\",\"UX_HOME\": \"/home/travis/build/CUL-DigitalServices/avocet-ui\",\"LOCAL_FILE_STORAGE_DIRECTORY\": \"/home/travis/build/CUL-DigitalServices/files\"}' > nginx/nginx.json"
  - grunt configNginx
  - sudo cp ./target/optimized/nginx/nginx.conf /etc/nginx/nginx.conf
  - sudo mkdir /usr/share/nginx/logs
  - sudo service nginx start

  # Install Hilary and create our test tenant
  - git clone  --branch master --depth=1 git://github.com/CUL-DigitalServices/avocet-hilary.git ../avocet-hilary
  - cd ../avocet-hilary
  - npm install --production
  - node app.js &

  # Wait for Hilary to have started up
  - cd ../avocet-ui
  - ./tools/travis/checkHilaryStart.sh

  # Create a test tenant
  - ADMIN_COOKIE=$(curl -s --cookie-jar - -d"username=administrator" -d"password=administrator"  -e "/" http://admin.oae.com/api/auth/login | grep connect.sess | cut -f 7)
  - curl --cookie connect.sess=${ADMIN_COOKIE} -e "/" -d"alias=cam" -d"displayName=Cambridge" -d"host=cam.oae.com" http://admin.oae.com/api/tenant/create
  - curl --cookie connect.sess=${ADMIN_COOKIE} -e "/" -d"oae-principals/recaptcha/enabled=false" http://admin.oae.com/api/config

addons:
  hosts:
    - cam.oae.com
    - admin.oae.com

services:
  - elasticsearch
  - rabbitmq
  - redis-server

after_success:
  - etc/scripts/travis-upload.sh

notifications:
  irc: "irc.freenode.org#ucam-ds-oa"
