language: node_js
node_js:
  - 0.10

branches:
  only:
    - master

env:
  global:
    - secure: ckul1NeOfQi13LxMvppoXzc/O08YEf2HqDbyE3dl2mgnjQVfB8ASRKSyvp6jZhKYEPX+WUwfdpHid8fGq3ESwTAUT41QF+HBUr7xdz6772m7Qm0nMJ94FaT7iL+2sR2O6WmqpWWktUSOkN4omI7xOv9b1MVHYiYPct965SM3SdI=
    - secure: gJlW/YbFeC7HAiFxH+M4Ia8BYP0n4PvLRT2bG5YgfFsRfF7yNkppCIt/cSxrl5SUhsT6UnArLVejP1nw6U6Pxu4KoOKdnWLnFjU2/qtU0IpEZDgex4u1wthxe37qd/fkNRq5U243c4N9UuY8YLJm0rDVYhxVsP1QQSymWThhis4=

addons:
  hosts:
    - cam.oae.com
    - admin.oae.com

script:
  - true

services:
  - elasticsearch
  - rabbitmq
  - redis-server

after_success:
  # Package and upload to Amazon S3
  - etc/scripts/travis-upload.sh

notifications:
  irc: "irc.freenode.org#ucam-ds-oa"
