language: node_js
node_js:
  - 0.10

branches:
  only:
    - master

before_install:
  - sudo sed -e 's/^\(127\.0\.0\.1.*\)$/\1 admin.oae.com test.oae.com/' --in-place /etc/hosts
  - sudo sed -e 's/^\(::1.*\)$/\1 admin.oae.com test.oae.com/' --in-place /etc/hosts
  - cd ../
  - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-i686.tar.bz2 
  - tar xjf phantomjs-1.9.2-linux-i686.tar.bz2
  - sudo ln -fs pwd/phantomjs-1.9.2-linux-i686/bin/phantomjs /usr/local/bin/phantomjs
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  - sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs
  - casperjs --version
  - phantomjs --version
  - cd ../3akai-ux
  - npm install -d
  - "echo '{\"NGINX_USER\": \"root\",\"NGINX_GROUP\": \"root\",\"NGINX_HOSTNAME\": \"admin.oae.com\",\"UX_HOME\": \"/home/travis/build/oaeproject/3akai-ux\",\"LOCAL_FILE_STORAGE_DIRECTORY\": \"/home/travis/build/oaeproject/files\"}' > nginx/nginx.json"
  - grunt configNginx
  - sudo apt-get -y install python-software-properties
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install nginx-full
  - sudo cp ./target/optimized/nginx/nginx.conf /etc/nginx/nginx.conf
  - sudo mkdir /usr/share/nginx/logs
  - sudo service nginx start
  - cd ../
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra stop
  - sudo service cassandra start
  - sudo service cassandra status
  - sudo service mysql stop
  - sudo service memcached stop
  - sudo service postgresql stop
  - sudo apt-get install -qq graphicsmagick
  - npm install -g grunt-cli
  - git clone git://github.com/ether/etherpad-lite --branch master etherpad-lite
  - cd etherpad-lite
  - echo "13SirapH8t3kxUh5T5aqWXhXahMzoZRA" > APIKEY.txt
  - ./bin/installDeps.sh
  - "sed -i 's/defaultPadText\" : \".*\"/defaultPadText\" : \"\"/g' settings.json"
  - node src/node/server.js &
  - git clone git://github.com/oaeproject/Hilary.git --branch master ../Hilary
  - cd ../Hilary
  - npm install -d
  - node app.js &
  - sleep 20
  - cd ../3akai-ux

services:
  - cassandra
  - elasticsearch
  - rabbitmq
  - redis-server

script:
  - grunt test --qunit-host test.oae.com

notifications:
  email:
    - oae-team@collab.sakaiproject.org
  irc: "irc.freenode.org#sakai"
